/**
 * Build an SVG sprite from a curated subset of Lucide icons.
 * relay-design-systemのscripts/build-icons.mjsを簡略化したもの。
 *
 *   input:  node_modules/lucide-static/icons/{name}.svg
 *   output: dist/icons.svg, preview/icons.svg
 *
 *   各Lucideソースを <symbol id="lucide-{name}"> でラップする。
 *   <svg class="icon icon-md"><use href="…#lucide-search" /></svg> で参照する。
 *
 *   アイコンを増やすには ICONS リストに追記して再実行する。
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");

export const ICONS = [
  // Action
  "plus", "x", "check", "pencil", "trash-2",
  // Navigation
  "chevron-up", "chevron-down", "chevron-left", "chevron-right", "menu", "more-horizontal",
  // Table（並べ替え・絞り込み）
  "arrow-up", "arrow-down", "arrow-up-down", "funnel",
  // Date / File / List
  "calendar", "chevrons-left", "chevrons-right", "cloud-upload", "file", "download", "grip-vertical", "minus",
  // Status
  "info", "check-circle", "alert-triangle", "alert-circle",
  // Search / Visibility
  "search", "eye", "eye-off",
  // Object
  "external-link", "settings", "user",
];

const SOURCE_DIR = path.join(projectRoot, "node_modules", "lucide-static", "icons");
const OUT_PATHS = [
  path.join(projectRoot, "dist", "icons.svg"),
  path.join(projectRoot, "preview", "icons.svg"),
];

const KEEP_ATTRS = new Set(["viewBox", "fill", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin"]);

function extractSvgAttrs(svgOpenTag) {
  const attrs = {};
  for (const m of svgOpenTag.matchAll(/(\S+?)\s*=\s*"([^"]*)"/g)) {
    if (KEEP_ATTRS.has(m[1])) attrs[m[1]] = m[2];
  }
  return attrs;
}

function attrsToString(attrs) {
  return Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(" ");
}

async function convertOne(name) {
  const filePath = path.join(SOURCE_DIR, `${name}.svg`);
  if (!existsSync(filePath)) {
    throw new Error(`Icon "${name}" not found at ${filePath}. ICONSリストの名前を確認してください。`);
  }
  const raw = await readFile(filePath, "utf8");
  const openMatch = raw.match(/<svg\b[^>]*>/);
  if (!openMatch) throw new Error(`No <svg> open tag in ${filePath}`);
  const attrs = extractSvgAttrs(openMatch[0]);

  const inner = raw
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<svg\b[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim()
    .split("\n")
    .map((line) => "    " + line.trim())
    .filter((line) => line.trim().length > 0)
    .join("\n");

  return `  <symbol id="lucide-${name}" ${attrsToString(attrs)}>\n${inner}\n  </symbol>`;
}

async function main() {
  console.log(`Building Lucide sprite (${ICONS.length} icons)…`);
  const symbols = await Promise.all(ICONS.map(convertOne));
  const out = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- Generated by scripts/build-icons.mjs. Source: lucide-static (ISC). -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">`,
    `  <defs>`,
    ...symbols,
    `  </defs>`,
    `</svg>`,
    ``,
  ].join("\n");

  const sizeKb = (Buffer.byteLength(out, "utf8") / 1024).toFixed(1);
  for (const p of OUT_PATHS) {
    await mkdir(path.dirname(p), { recursive: true });
    await writeFile(p, out, "utf8");
    console.log(`✓ Wrote ${path.relative(projectRoot, p)} (${sizeKb} KB, ${ICONS.length} icons)`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
